"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { BookOpenCheck, Brain, CalendarDays, Check, ChevronLeft, ChevronRight, ClipboardCheck, Flame, Plus, Target, TrendingUp, ArrowUpRight, CircleDotDashed, Sparkles } from "lucide-react";
import { useBook } from "@/components/BookProvider";
import { fmtMoney, frDate, todayISO } from "@/lib/format";
import { LogTradeModal } from "@/components/modals";
import { Area } from "@/components/charts";

const MINDSETS = [{ id: "calm", label: "Calme", detail: "Présent et lucide" }, { id: "neutral", label: "Neutre", detail: "Stable, sans excès" }, { id: "tense", label: "Tendu", detail: "À surveiller" }, { id: "tilt", label: "Tilt", detail: "Session à couper" }];
const shiftDay = (date, amount) => { const value = new Date(`${date}T12:00:00`); value.setDate(value.getDate() + amount); return value.toISOString().slice(0, 10); };

export default function JournalPage() {
  const { scopedTrades, dailyReviews, saveDailyReview } = useBook();
  const [date, setDate] = useState(todayISO()); const [logOpen, setLogOpen] = useState(false); const [saving, setSaving] = useState(false); const [draft, setDraft] = useState(null);
  const review = dailyReviews.find((item) => item.date === date);
  const form = draft || review || { mindset: "", respected_plan: null, lesson: "", intention: "" };
  const dayTrades = useMemo(() => scopedTrades.filter((trade) => trade.date === date), [scopedTrades, date]);
  const pnl = dayTrades.reduce((sum, trade) => sum + Number(trade.pnl || 0), 0);
  const planned = dayTrades.filter((trade) => trade.plan).length;
  const checked = dayTrades.filter((trade) => trade.setup && (trade.strategy_checks || []).length > 0).length;
  const discipline = dayTrades.length ? Math.round((planned / dayTrades.length) * 70 + (checked / dayTrades.length) * 30) : 0;
  const streak = useMemo(() => { let count = 0; let cursor = todayISO(); const saved = new Set(dailyReviews.map((item) => item.date)); while (saved.has(cursor)) { count += 1; cursor = shiftDay(cursor, -1); } return count; }, [dailyReviews]);
  const pulse = useMemo(() => {
    const days = Array.from({ length: 7 }, (_, index) => shiftDay(date, index - 6));
    const daily = days.map((day) => scopedTrades.filter((trade) => trade.date === day).reduce((sum, trade) => sum + Number(trade.pnl || 0), 0));
    let running = 0;
    return { days, values: daily.map((value) => { running += value; return running; }) };
  }, [scopedTrades, date]);
  const update = (patch) => setDraft({ ...form, ...patch });
  const save = async () => { setSaving(true); await saveDailyReview(date, { mindset: form.mindset || null, respected_plan: form.respected_plan, lesson: form.lesson || null, intention: form.intention || null }); setDraft(null); setSaving(false); };
  const isToday = date === todayISO();
  return <div className="journal-command min-h-full bg-prism-bg p-4 text-white sm:p-6 lg:p-8"><div className="journal-grid" aria-hidden="true" /><div className="mx-auto max-w-[1280px]">
    <header className="journal-header mb-6 flex flex-col justify-between gap-5 pb-6 lg:flex-row lg:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-prism-accent"><CircleDotDashed className="h-4 w-4" /> Review loop · journal</div><h1 className="text-3xl font-semibold tracking-[-0.05em] sm:text-4xl">Le cockpit de tes décisions.</h1><p className="mt-2 text-sm text-prism-muted">Exécution, discipline et apprentissage — une seule boucle de progression.</p></div><div className="flex items-center gap-2"><button type="button" onClick={() => { setDate(shiftDay(date, -1)); setDraft(null); }} className="journal-icon-button" aria-label="Jour précédent"><ChevronLeft /></button><button type="button" onClick={() => { setDate(todayISO()); setDraft(null); }} className="journal-date-button">{isToday ? "Aujourd’hui" : frDate(date)}</button><button type="button" disabled={isToday} onClick={() => { setDate(shiftDay(date, 1)); setDraft(null); }} className="journal-icon-button disabled:opacity-30" aria-label="Jour suivant"><ChevronRight /></button></div></header>
    <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<TrendingUp />} label="P&L de la session" value={fmtMoney(pnl)} tone={pnl >= 0 ? "text-prism-win" : "text-prism-loss"} /><Metric icon={<Target />} label="Discipline" value={dayTrades.length ? `${discipline}/100` : "—"} tone="text-prism-accent" /><Metric icon={<ClipboardCheck />} label="Plan respecté" value={dayTrades.length ? `${planned}/${dayTrades.length}` : "—"} /><Metric icon={<Flame />} label="Routine" value={`${streak} jour${streak > 1 ? "s" : ""}`} tone="text-orange-300" /></div>
    <section className="journal-pulse mb-6 grid gap-5 rounded-2xl border border-prism-line p-4 sm:p-5 lg:grid-cols-[1.45fr_.55fr]"><div><div className="flex items-center justify-between gap-3"><div><p className="journal-kicker">Performance pulse</p><h2 className="mt-1 text-lg font-semibold">Trajectoire sur 7 jours</h2></div><span className="journal-live"><span /> En suivi</span></div><div className="mt-4 h-[122px]"><Area values={pulse.values} labels={pulse.days.map(frDate)} fmt={fmtMoney} color="var(--prism-accent)" fill="var(--prism-accent)" /></div></div><div className="journal-edge"><Sparkles className="h-4 w-4 text-prism-accent" /><p className="journal-kicker mt-3">Signal du jour</p><p className="mt-2 text-sm font-semibold leading-relaxed">{!dayTrades.length ? "Une session sans trade reste une victoire si tu as protégé ton plan." : discipline >= 85 ? "Exécution propre. Ne change rien à ce qui est reproductible." : "La prochaine progression est dans le respect strict de tes critères."}</p><Link href="/trade-logs" className="journal-link mt-4">Ouvrir les recaps <ArrowUpRight className="h-4 w-4" /></Link></div></section>
    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section className="rounded-2xl border border-prism-line bg-prism-panel p-4 sm:p-5"><div className="mb-5 flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">Revue de session</h2><p className="mt-1 text-sm text-prism-muted">À remplir en moins d’une minute, une fois les marchés fermés.</p></div><span className="rounded-full border border-prism-line px-2.5 py-1 text-xs text-prism-muted">{frDate(date)}</span></div><div className="mb-5"><label className="journal-label"><Brain className="h-4 w-4" /> Comment étais-tu ?</label><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">{MINDSETS.map((mindset) => <button key={mindset.id} type="button" onClick={() => update({ mindset: mindset.id })} className={`rounded-xl border p-3 text-left transition ${form.mindset === mindset.id ? "border-prism-accent bg-prism-accentDim text-white" : "border-prism-line bg-black/20 text-prism-muted hover:border-prism-line2 hover:text-white"}`}><span className="block text-sm font-semibold">{mindset.label}</span><span className="mt-1 block text-xs opacity-70">{mindset.detail}</span></button>)}</div></div><div className="mb-5"><label className="journal-label"><Check className="h-4 w-4" /> As-tu respecté ton plan ?</label><div className="mt-2 flex gap-2">{[[true, "Oui, propre"], [false, "Non, j’ai dévié"]].map(([value, label]) => <button key={String(value)} type="button" onClick={() => update({ respected_plan: value })} className={`rounded-xl border px-4 py-2.5 text-sm font-semibold transition ${form.respected_plan === value ? "border-prism-accent bg-prism-accentDim text-white" : "border-prism-line text-prism-muted hover:text-white"}`}>{label}</button>)}</div></div><label className="journal-label">La leçon du jour</label><textarea value={form.lesson || ""} onChange={(event) => update({ lesson: event.target.value })} maxLength={500} placeholder="Ex. Après deux pertes, je ne force pas une troisième entrée." className="journal-textarea" /><label className="journal-label mt-4">Mon intention pour demain</label><textarea value={form.intention || ""} onChange={(event) => update({ intention: event.target.value })} maxLength={500} placeholder="Ex. Attendre mon setup A+ à l’ouverture de New York." className="journal-textarea" /><div className="mt-5 flex justify-end"><button type="button" onClick={save} disabled={saving} className="trade-primary-action disabled:opacity-50">{saving ? "Sauvegarde…" : "Sauvegarder ma revue"}</button></div></section>
    <aside className="rounded-2xl border border-prism-line bg-prism-panel p-4 sm:p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Décisions du jour</h2><p className="mt-1 text-sm text-prism-muted">{dayTrades.length ? `${dayTrades.length} trade${dayTrades.length > 1 ? "s" : ""} enregistré${dayTrades.length > 1 ? "s" : ""}` : "Aucun trade pour le moment"}</p></div><CalendarDays className="h-5 w-5 text-prism-accent" /></div>{dayTrades.length ? <div className="mt-5 space-y-2">{dayTrades.map((trade) => <Link href="/trade-logs" key={trade.id} className="block rounded-xl border border-prism-line bg-black/20 p-3 transition hover:border-prism-line2"><div className="flex justify-between gap-3"><div><span className="font-mono font-bold">{trade.symbol}</span><span className={`ml-2 text-xs font-semibold ${trade.dir === "long" ? "text-prism-win" : "text-prism-loss"}`}>{trade.dir?.toUpperCase()}</span><p className="mt-1 text-xs text-prism-muted">{trade.setup || "Sans stratégie"} · {trade.grade || "—"}</p></div><span className={`font-mono font-bold ${Number(trade.pnl) >= 0 ? "text-prism-win" : "text-prism-loss"}`}>{fmtMoney(trade.pnl)}</span></div></Link>)}</div> : <div className="mt-5 rounded-xl border border-dashed border-prism-line p-6 text-center"><p className="text-sm text-prism-muted">Une journée sans trade peut aussi être une journée disciplinée.</p><button type="button" onClick={() => setLogOpen(true)} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-prism-accent hover:text-white"><Plus className="h-4 w-4" /> Logger un trade</button></div>}<div className="mt-5 rounded-xl border border-prism-accent/20 bg-prism-accentDim/40 p-4"><p className="text-xs font-bold uppercase tracking-widest text-prism-accent">Lecture rapide</p><p className="mt-2 text-sm leading-relaxed text-prism-muted">{!dayTrades.length ? "Commence par ta revue : elle compte même quand tu ne prends aucune position." : discipline >= 85 ? "Très bonne exécution : garde ce niveau de sélectivité." : planned < dayTrades.length ? "Tu as dévié du plan sur une ou plusieurs entrées. Note le déclencheur précis." : "Tes entrées sont dans le plan ; vérifie la qualité de ta checklist."}</p></div></aside></div><div className="mt-6 flex justify-end"><Link href="/trade-logs" className="text-sm font-semibold text-prism-muted hover:text-white">Voir toutes les archives →</Link></div>{logOpen && <LogTradeModal onClose={() => setLogOpen(false)} />}
  </div></div>;
}
function Metric({ icon, label, value, tone = "text-white" }) { return <div className="journal-metric rounded-2xl border border-prism-line bg-prism-panel p-4"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-prism-muted">{icon}{label}</div><div className={`mt-3 font-mono text-2xl font-bold ${tone}`}>{value}</div></div>; }
