"use client";

import { use, useState } from "react";
import { useRouter } from "next/navigation";
import { useBook } from "@/components/BookProvider";
import { AccountModal } from "@/components/modals";
import { FirmDot, Pill, GhostBtn } from "@/components/ui";
import { firmColor, STATUS_LABEL } from "@/lib/constants";
import { fmtMoney, frDate } from "@/lib/format";
import { accountHealth, signedMoney } from "@/lib/accountHealth";
import { ArrowLeft, Pencil, Trash2, Printer } from "lucide-react";

export default function AccountDetailPage({ params }) {
  const resolvedParams = use(params);
  const accountId = resolvedParams.id;
  const router = useRouter();
  const { accounts, trades, certificates, deleteAccount, lang, t } = useBook();
  const [editModal, setEditModal] = useState(false);

  const L = lang === "en" ? "en" : "fr";
  const account = accounts.find((a) => String(a.id) === String(accountId));

  if (!account) {
    return (
      <div className="flex flex-col items-center justify-center py-16 text-center">
        <p className="text-lg font-semibold text-white">
          {L === "en" ? "Account not found" : "Compte introuvable"}
        </p>
        <GhostBtn className="mt-4" onClick={() => router.push("/accounts")}>
          <ArrowLeft size={16} className="mr-2" />
          {L === "en" ? "Back to accounts" : "Retour aux comptes"}
        </GhostBtn>
      </div>
    );
  }

  const h = accountHealth(account, trades, certificates, L);
  const accountTrades = trades.filter((tr) => String(tr.account_id) === String(account.id));
  const isEval = !(account.type === "funded" || account.status === "funded" || account.status === "passed");
  const stStyle = STATUS_LABEL[account.status] || ["gray", account.status];

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6 print:p-6 print:text-black print:bg-white">
      {/* Header / Navigation (masqué à l'impression) */}
      <div className="flex items-center justify-between print:hidden">
        <GhostBtn onClick={() => router.push("/accounts")} className="text-xs">
          <ArrowLeft size={14} className="mr-1.5" />
          {L === "en" ? "Accounts" : "Comptes"}
        </GhostBtn>
        <div className="flex items-center gap-2">
          <GhostBtn onClick={handlePrint} className="text-xs text-accent">
            <Printer size={14} className="mr-1.5" />
            {L === "en" ? "Export PDF / Print" : "Exporter PDF / Imprimer"}
          </GhostBtn>
          <GhostBtn onClick={() => setEditModal(true)} className="text-xs">
            <Pencil size={14} className="mr-1.5" />
            {L === "en" ? "Edit" : "Éditer"}
          </GhostBtn>
          <GhostBtn
            onClick={() => {
              if (window.confirm(L === "en" ? "Delete this account?" : "Supprimer ce compte ?")) {
                deleteAccount(account.id);
                router.push("/accounts");
              }
            }}
            className="text-xs text-loss hover:bg-lossDim"
          >
            <Trash2 size={14} className="mr-1.5" />
            {L === "en" ? "Delete" : "Supprimer"}
          </GhostBtn>
        </div>
      </div>

      {/* En-tête Rapport d'impression */}
      <div className="hidden print:block border-b border-gray-300 pb-4 mb-4">
        <h1 className="text-2xl font-bold">
          {L === "en" ? "Trading Performance Report" : "Rapport de Performance Trading"}
        </h1>
        <p className="text-sm text-gray-600">
          {L === "en" ? "Generated by My Funded Book" : "Généré par My Funded Book"} — {frDate(new Date().toISOString())}
        </p>
      </div>

      {/* Carte d'information principale */}
      <div className="rounded-2xl border border-line bg-panel p-5 print:border-gray-300 print:bg-gray-50 print:text-black">
        <div className="flex items-start justify-between">
          <div>
            <div className="flex items-center gap-2 text-xl font-bold text-white print:text-black">
              <FirmDot color={firmColor(account.firm)} />
              <span>{account.firm}</span>
            </div>
            <div className="mt-2 flex flex-wrap gap-2">
              <Pill tone="gray">{fmtMoney(account.size)}</Pill>
              <Pill tone={isEval ? "yellow" : "green"}>
                {isEval ? t("acc_eval") : t("acc_funded")}
              </Pill>
              <Pill tone={stStyle[0]}>{stStyle[1]}</Pill>
            </div>
            {account.note && <p className="mt-2 text-sm text-muted2 print:text-gray-700">{account.note}</p>}
          </div>
          <div className="text-right">
            <div className="text-xs text-muted2 print:text-gray-600">{L === "en" ? "Current PnL" : "PnL Actuel"}</div>
            <div className={`font-mono text-2xl font-extrabold ${h.netPnL >= 0 ? "text-accent print:text-green-700" : "text-loss print:text-red-700"}`}>
              {signedMoney(h.netPnL)}
            </div>
          </div>
        </div>
      </div>

      {/* Grille de métriques */}
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <div className="rounded-xl border border-line bg-panel p-4 print:border-gray-300 print:bg-gray-50">
          <div className="text-xs text-muted2 print:text-gray-600">{L === "en" ? "Trades logged" : "Trades enregistrés"}</div>
          <div className="mt-1 font-mono text-xl font-bold text-white print:text-black">{accountTrades.length}</div>
        </div>
        <div className="rounded-xl border border-line bg-panel p-4 print:border-gray-300 print:bg-gray-50">
          <div className="text-xs text-muted2 print:text-gray-600">{L === "en" ? "Max Drawdown" : "Drawdown Max"}</div>
          <div className="mt-1 font-mono text-xl font-bold text-white print:text-black">
            {account.max_drawdown ? fmtMoney(account.max_drawdown) : "—"}
          </div>
        </div>
        <div className="rounded-xl border border-line bg-panel p-4 print:border-gray-300 print:bg-gray-50">
          <div className="text-xs text-muted2 print:text-gray-600">{L === "en" ? "Daily Loss Limit" : "Perte max / jour"}</div>
          <div className="mt-1 font-mono text-xl font-bold text-white print:text-black">
            {account.daily_loss_limit ? fmtMoney(account.daily_loss_limit) : "—"}
          </div>
        </div>
        <div className="rounded-xl border border-line bg-panel p-4 print:border-gray-300 print:bg-gray-50">
          <div className="text-xs text-muted2 print:text-gray-600">{L === "en" ? "Profit Target" : "Objectif de profit"}</div>
          <div className="mt-1 font-mono text-xl font-bold text-white print:text-black">
            {account.profit_target ? fmtMoney(account.profit_target) : "—"}
          </div>
        </div>
      </div>

      {/* Section Liste des Trades pour le Rapport */}
      <div className="rounded-2xl border border-line bg-panel p-5 print:border-gray-300 print:bg-white">
        <h3 className="text-sm font-semibold text-white print:text-black mb-3">
          {L === "en" ? "Trade History" : "Historique des Trades"}
        </h3>
        {accountTrades.length === 0 ? (
          <p className="text-xs text-muted2 print:text-gray-500">
            {L === "en" ? "No trades recorded for this account." : "Aucun trade enregistré pour ce compte."}
          </p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs text-muted2 print:text-black">
              <thead className="border-b border-line text-white print:border-gray-300 print:text-black">
                <tr>
                  <th className="pb-2">{L === "en" ? "Date" : "Date"}</th>
                  <th className="pb-2">{L === "en" ? "Asset" : "Actif"}</th>
                  <th className="pb-2">{L === "en" ? "Type" : "Sens"}</th>
                  <th className="pb-2 text-right">{L === "en" ? "Result ($)" : "Résultat ($)"}</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-line/50 print:divide-gray-200">
                {accountTrades.map((tr) => (
                  <tr key={tr.id}>
                    <td className="py-2">{frDate(tr.date || tr.created_at)}</td>
                    <td className="py-2 font-semibold text-white print:text-black">{tr.symbol || tr.asset || "—"}</td>
                    <td className="py-2">{tr.side || "BUY"}</td>
                    <td className={`py-2 text-right font-mono font-bold ${(tr.pnl || 0) >= 0 ? "text-accent print:text-green-700" : "text-loss print:text-red-700"}`}>
                      {signedMoney(tr.pnl || 0)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Modal Édition */}
      {editModal && (
        <AccountModal editing={account} onClose={() => setEditModal(false)} />
      )}
    </div>
  );
}
